name: "Get number of shards"
description: "Get the number of nf-test shards for the current CI job"
outputs:
  shards:
    description: "Array of shard numbers"
    value: ${{ steps.shards.outputs.shards }}
  total_shards:
    description: "Total number of shards"
    value: ${{ steps.shards.outputs.total_shards }}
  tags:
    description: "Tags to test (`<tags>[,<tags>...]`)"
    value: ${{ steps.shards.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Install nf-test
      uses: nf-core/setup-nf-test@v1
      with:
        version: ${{ env.NFT_VER }}

    - name: Get number of shards
      shell: bash
      run: |
        nftest_output=$(nf-test test --dry-run --changed-since HEAD^ --filter process --follow-dependencies)
        if nftest_output | grep -q 'No tests found'; then
          shards = []
          total_shards=0
        fi
        number_of_shards=$(echo $nftest_output | grep -o 'Found [0-9]* related test' | tail -1 | awk '{print $2}')
        three_tests_per_shard=$(echo $(($number_of_shards / 3)) | awk '{print int($1+0.5)}')
        shards_array=$(for shard in $(seq 1 $number_of_shards); do echo $shard; done | tr ' ' '\n' | jq -R . | jq -s .)
        tags = $(echo $nftest_output | grep -o 'tag [^ ]*' | tail -1 | awk '{print $2}')
        echo "shards=${shards_array}" >> $GITHUB_OUTPUT
        echo "total_shards=${number_of_shards}" >> $GITHUB_OUTPUT
        echo "tags=${tags}" >> $GITHUB_OUTPUT
